# Generated by Django 4.2.6 on 2024-10-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Camioneta', 'Camioneta')], max_length=20)),
                ('transmision', models.CharField(choices=[('Automática', 'Automática'), ('Manual', 'Manual')], max_length=20)),
                ('combustible', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Híbrido', 'Híbrido'), ('Eléctrico', 'Eléctrico')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometraje', models.IntegerField()),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], max_length=20)),
            ],
        ),
    ]
