# Generated by Django 4.2.6 on 2024-11-08 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='combustible',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='kilometraje',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='Vehiculo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='airbag_conductor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='airbag_pasajero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='aire_acondicionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='alarma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad_personas',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='comando_remoto_radio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='computadora_abordo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='control_estabilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='control_traccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='dimensiones',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='direccion',
            field=models.CharField(default='delantera', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='distancia_entre_ejes',
            field=models.FloatField(default='1,5'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='frenos_abs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometros',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='motor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='piloto_automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='potencia',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='puertas',
            field=models.PositiveIntegerField(default='4'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='sensor_estacionamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='sensor_lluvia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_carroceria',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(default='Nafta', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='traccion_asr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='valvulas_por_cilindro',
            field=models.PositiveIntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='año',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='transmision',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ImagenPersonajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(upload_to='Personajes')),
                ('Codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Imagenes', to='App.vehiculo')),
            ],
        ),
    ]
