# Generated by Django 4.2.6 on 2024-11-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_vehiculo_distancia_entre_ejes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='distancia_entre_ejes',
            field=models.FloatField(default=1.5),
        ),
    ]
