# Generated by Django 4.2.6 on 2024-11-08 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_vehiculo_distancia_entre_ejes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='distancia_entre_ejes',
        ),
    ]
